services:
  M-team-notifier:
    image: ghcr.io/gm13282/m-team-weekly:main
    container_name: M-team-notifier
    environment:
      API_URL: "https://kp.m-team.cc/api/torrent/search"
      API_KEY: "Your_API_Key"
      MODE: "adult" # normal,adult,movie,music,tvshow,waterfall,rss,rankings
      PAGE_NUMBER: 1
      PAGE_SIZE: 25
      CHECK_INTERVAL: 3600 # update per hour
      AUTH_USERNAME: "name@email.com" # ntfy.sh user
      AUTH_PASSWORD: "password" # ntfy.sh password
      NOTIFICATION_URL: "https://ntfy.sh/" 
      NOTIFICATION_TOPIC: "my_topic" # ntfy.sh topic
      NOTIFICATION_TITLE: "Name your title" # name your title
      NOTIFICATION_PRIORITY: 3 # If you don't know how to modify it, please keep the 3
      NOTIFICATION_ACTIONS: '[{"action": "view", "label": "点击查看", "url": "https://kp.m-team.cc"}]'
      MESSAGE_MODE: 1 # If 1 will message the topic's name, 0 just "活動置頂"